biru/urls.py
from django.urls import path, include
from .views import *
app_name = 'biru'
urlpatterns = [ 

	path('balai_pengobatan/', balai_pengobatan, name='balai_pengobatan'), 
	path('create_balai_pengobatan/', create_balai_pengobatan, name='create_balai_pengobatan'),
	path('update_balai_pengobatan/', update_balai_pengobatan, name='update_balai_pengobatan'),
	path('delete_balai_pengobatan/', delete_balai_pengobatan, name='delete_balai_pengobatan'),   
 
	path('obat/', obat, name='obat'), 
	path('create_obat/', create_obat, name='create_obat'),
	path('update_obat/', update_obat, name='update_obat'),
	path('delete_obat/', delete_obat, name='delete_obat'),

]

farmakami/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('biru/', include('biru.urls')),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('merah/', include('merah.urls')),
    path('ungu/', include('ungu.urls')),
    path('', include('fkauth.urls'))
]

biru/models.py
from django.db import models

# Create your models here.

biru/forms.py
from django import forms
from django.forms import Form
from django.db import connection, transaction, IntegrityError

class Balai_Pengobatan_Form(forms.Form):

	APOTEK_CHOICES = []

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		with connection.cursor() as cursor:
			cursor.execute("SELECT id_apotek, id_apotek FROM APOTEK")
			self.fields['id_apotek'].choices = cursor.fetchall()

	pos_attrs = {
		'class': 'form-control',
		
	}
	alamat_balai = forms.CharField(label="Alamat Balai", widget=forms.TextInput(attrs=pos_attrs), required=True)
	nama_balai = forms.CharField(label='Nama Balai', required=True, max_length=50, widget=forms.TextInput(attrs=pos_attrs))   
	jenis_balai = forms.CharField(label="Jenis Balai", required=True, max_length=30, widget=forms.TextInput(attrs=pos_attrs))
	telepon_balai = forms.CharField(label="Telepon Balai", required=False, max_length=20, widget=forms.NumberInput(attrs=pos_attrs))
	id_apotek = forms.ChoiceField(label='ID Apotek yang Berasosiasi', required=True, choices=APOTEK_CHOICES,
								widget=forms.Select(attrs={'class': 'form-control'}))
  
class Update_Balai_Pengobatan_Form(Balai_Pengobatan_Form):

	id_balai = forms.CharField(label="ID Balai",
		widget=forms.TextInput(attrs={'class': 'form-control',
									  'readonly': True}),
		max_length=10
	)

	def save(self):
		cd = self.cleaned_data
		with connection.cursor() as cursor:
			cursor.execute("""
			UPDATE BALAI_PENGOBATAN SET alamat_balai = %s, nama_balai = %s, jenis_balai = %s,
			telepon_balai = %s
			WHERE id_balai = %s """,
						   [cd.get("alamat_balai"), cd.get("nama_balai"),
							cd.get("jenis_balai"), cd.get("telepon_balai"),
							cd.get("id_balai")])
			cursor.execute("""
			UPDATE BALAI_APOTEK SET id_apotek = %s
			WHERE id_balai = %s""", [cd.get("id_apotek"), cd.get("id_balai")])

			cursor.execute("""SELECT id_balai FROM BALAI_APOTEK""")
			balai_berasosiasi = cursor.fetchall()
			if cd.get("id_balai") not in balai_berasosiasi:
				cursor.execute("INSERT INTO BALAI_APOTEK VALUES(%s, %s)",
						   [cd.get("id_balai"), cd.get("id_apotek")
							])

		


class Create_Balai_Pengobatan_Form(Balai_Pengobatan_Form):
	def clean_alamat_balai(self):
		data = self.cleaned_data.get('alamat_balai')
		with connection.cursor() as cursor:
			cursor.execute("SELECT * FROM BALAI_PENGOBATAN WHERE alamat_balai=%s LIMIT 1",
						   [data])
			row = cursor.fetchone()
		if row is not None:
			raise forms.ValidationError("Alamat balai yang dimasukkan harus unik")
		return data

	def save(self):
		cd = self.cleaned_data
		with connection.cursor() as cursor:
			cursor.execute("SELECT * FROM BALAI_PENGOBATAN ORDER BY id_balai DESC LIMIT 1")
			add_id_balai = int(cursor.fetchone()[0][3:]) + 1
			new_id_balai= f"FBP{add_id_balai:07}"
		
			cursor.execute("INSERT INTO BALAI_PENGOBATAN VALUES(%s, %s, %s, %s, %s)",
						   [new_id_balai, cd.get("alamat_balai"), cd.get("nama_balai"),
							cd.get("jenis_balai"), cd.get("telepon_balai")
							])
			cursor.execute("INSERT INTO BALAI_APOTEK VALUES(%s, %s)",
						   [new_id_balai, cd.get("id_apotek")
							])  
  


class Obat_Form(forms.Form):

	MERK_OBAT_CHOICES = []

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		with connection.cursor() as cursor:
			cursor.execute("SELECT id_merk_obat, id_merk_obat FROM MERK_OBAT")
			self.fields['id_merk_obat'].choices = cursor.fetchall()


	pos_attrs = {
		'class': 'form-control',

	}
	id_merk_obat = forms.ChoiceField(label='ID Merk Obat', required=True, choices= MERK_OBAT_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
	netto = forms.CharField(label="Netto", required=True, max_length=10, widget=forms.TextInput(attrs=pos_attrs))
	dosis = forms.CharField(label="Dosis", required=True, widget=forms.TextInput(attrs=pos_attrs))   
	aturan_pakai = forms.CharField(label="Aturan Pakai", required=False, widget=forms.TextInput(attrs=pos_attrs))
	kontraindikasi = forms.CharField(label="Kontraindikasi", required=False, widget=forms.TextInput(attrs=pos_attrs))
	bentuk_kesediaan = forms.CharField(label="Bentuk Kesediaan", required=True, widget=forms.TextInput(attrs=pos_attrs))


class Update_Obat_Form(Obat_Form):
	id_obat = forms.CharField(label="ID Obat",
		widget=forms.TextInput(attrs={'class': 'form-control',
									  'readonly': True}),
		max_length=10
	)

	id_produk = forms.CharField(label="ID Produk", 
		widget=forms.TextInput(attrs={'class': 'form-control',
									  'readonly': True}),
		max_length=10
	)


	def save(self):
		cd = self.cleaned_data
		with connection.cursor() as cursor:
			cursor.execute("""
			UPDATE OBAT SET id_merk_obat = %s, netto = %s, dosis = %s,
			aturan_pakai = %s, kontraindikasi = %s, bentuk_kesediaan = %s
			WHERE id_obat=%s """,
						   [cd.get("id_merk_obat"), cd.get("netto"),
							cd.get("dosis"), cd.get("aturan_pakai"),
							cd.get("kontraindikasi"), cd.get("bentuk_kesediaan"),
							cd.get("id_obat")])

class Create_Obat_Form(Obat_Form):
	def save(self):
		cd = self.cleaned_data
		with connection.cursor() as cursor:
			cursor.execute("SELECT * FROM OBAT ORDER BY id_obat DESC LIMIT 1")
			add_id_obat = int(cursor.fetchone()[0][3:]) + 1
			new_id_obat = f"FOB{add_id_obat:07}"
			cursor.execute("SELECT * FROM PRODUK ORDER BY id_produk DESC LIMIT 1")
			add_id_produk = int(cursor.fetchone()[0][3:]) + 1
			new_id_produk = f"FPK{add_id_produk:07}"
			cursor.execute("INSERT INTO PRODUK VALUES(%s)",
						   [new_id_produk])
			cursor.execute("INSERT INTO OBAT VALUES(%s, %s, %s, %s, %s, %s, %s, %s)",
						   [new_id_obat, new_id_produk, cd.get("id_merk_obat"), cd.get("netto"),
							cd.get("dosis"), cd.get("aturan_pakai"),
							cd.get("kontraindikasi"), cd.get("bentuk_kesediaan")
							])

biru/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import connection, transaction, IntegrityError
from .forms import *
from merah.views import user_login_required, cursor_fetchall


# Create your views here.
def balai_pengobatan(request):
	with connection.cursor() as cursor:
		# cursor.execute("SELECT * FROM BALAI_PENGOBATAN ORDER BY id_balai")
		cursor.execute(
			"""
			SELECT BP.id_balai, alamat_balai, nama_balai, jenis_balai, telepon_balai, nama_apotek
			FROM BALAI_PENGOBATAN as BP
			LEFT JOIN BALAI_APOTEK as BA
			ON BA.id_balai = BP.id_balai
			LEFT JOIN APOTEK as A
			ON BA.id_apotek = A.id_apotek
			ORDER BY BP.id_balai""")
		data_balai_pengobatan = cursor_fetchall(cursor)
	context = {'data': data_balai_pengobatan}
	return render(request, "BalaiPengobatan.html", context)
	

@user_login_required
def create_balai_pengobatan(request):

	if request.session.get("role") != "ADMIN_APOTEK":
		return redirect('biru:balai_pengobatan')
	if request.method == 'POST':
		form = Create_Balai_Pengobatan_Form(request.POST)
		if form.is_valid():
			form.save()
			return redirect("biru:balai_pengobatan")
	if request.method == 'GET':
		form = Create_Balai_Pengobatan_Form()
	context = {'form': form}
	return render(request, "CreateBalaiPengobatan.html", context)


@user_login_required
def update_balai_pengobatan(request):

	if request.session.get("role") != "ADMIN_APOTEK":
		return redirect('biru:balai_pengobatan')
	if request.method == 'POST':
		form = Update_Balai_Pengobatan_Form(request.POST)
		if form.is_valid():
			form.save()
			return redirect("biru:balai_pengobatan")
	elif request.method == 'GET':
		if request.GET.get('id_u_b') is None:
			return redirect('biru:balai_pengobatan')
		with connection.cursor() as cursor:
			cursor.execute("SELECT * FROM BALAI_PENGOBATAN where id_balai=%s LIMIT 1;",
							[request.GET.get('id_u_b')])
			data = cursor.fetchone()
			if data is None:
				return redirect('biru:balai_pengobatan')
			columns = [col[0] for col in cursor.description]
			data_balai_pengobatan = dict(zip(columns, data))

		form = Update_Balai_Pengobatan_Form(initial=data_balai_pengobatan)

	context = {'form': form}
	return render(request, "UpdateBalaiPengobatan.html", context)

@user_login_required
def delete_balai_pengobatan(request):
	if request.session.get("role") != "ADMIN_APOTEK":
		return redirect('biru:balai_pengobatan')
	if request.method == 'GET':
		if request.GET.get('id_d_b') is None:
			return redirect('biru:balai_pengobatan')
		else:
			id = request.GET.get('id_d_b')
			try:
				with connection.cursor() as cursor:
					with transaction.atomic():
						cursor.execute("""
						DELETE FROM BALAI_APOTEK WHERE id_balai=%s
						""", [id])
						cursor.execute("""
						DELETE FROM BALAI_PENGOBATAN WHERE id_balai=%s
						""", [id])
			except IntegrityError:
				pass
			return redirect('biru:balai_pengobatan')

def obat(request):
	with connection.cursor() as cursor:
		cursor.execute("SELECT * FROM OBAT ORDER BY id_obat")
		data_obat = cursor_fetchall(cursor)

	context = {'data': data_obat}
	return render(request, "Obat.html", context)


@user_login_required
def create_obat(request):
	if request.session.get("role") != "ADMIN_APOTEK" and request.session.get("role") != "CS" :
		return redirect('biru:obat')
	if request.method == 'POST':
		form = Create_Obat_Form(request.POST)
		if form.is_valid():
			form.save()
			return redirect("biru:obat")
	if request.method == 'GET':
		form = Create_Obat_Form()
	context = {'form': form}
	return render(request, "CreateObat.html", context)

	
@user_login_required
def update_obat(request):

	if request.session.get("role") != "ADMIN_APOTEK" and request.session.get("role") != "CS" :
		return redirect('biru:obat')
	if request.method == 'POST':
		form = Update_Obat_Form(request.POST)
		if form.is_valid():
			form.save()
			return redirect("biru:obat")
	elif request.method == 'GET':
		if request.GET.get('id_u_o') is None:
			return redirect('biru:obat')
		with connection.cursor() as cursor:
			cursor.execute("SELECT * FROM OBAT where id_obat=%s LIMIT 1;",
							[request.GET.get('id_u_o')])
			data = cursor.fetchone()
			if data is None:
				return redirect('biru:obat')
			columns = [col[0] for col in cursor.description]
			data_obat = dict(zip(columns, data))

		form = Update_Obat_Form(initial=data_obat)

	context = {'form': form}
	return render(request, "UpdateObat.html", context)

@user_login_required
def delete_obat(request):

	if request.session.get("role") != "ADMIN_APOTEK" and request.session.get("role") != "CS" :		
		return redirect('biru:obat')
	if request.method == 'GET':
		if request.GET.get('id_d_o') is None:
			return redirect('biru:obat')
		else:
			id = request.GET.get('id_d_o')
			try:
				with connection.cursor() as cursor:
					with transaction.atomic():
						cursor.execute("""
						DELETE FROM OBAT WHERE id_obat=%s
						""", [id])
			except IntegrityError:
				pass
			return redirect('biru:obat')

biru/templates/BalaiPengobatan.html
{% extends "base.html" %}
{% load static %}

{% block title %}Balai Pengobatan - Farmakami{% endblock %}

   
   
{% block content %}

	<div class='jumbotron justify-content-center' align="center">
        <h1>Daftar Balai Pengobatan</h1>
        <hr>
        <h4>Farmakami</h4>
    </div>


	<div class="container d-flex justify-content-center" align="center">
			
	<table class="table table-hover" align="center">
		<thead class="thead-dark">
			
				<th>ID Balai</th>
				<th>Alamat Balai</th>
				<th>Nama Balai</th>
				<th>Jenis Balai</th>
				<th>No. Telepon</th>
                <th>Apotek yang berasosiasi</th>
				{% if request.session.role == 'ADMIN_APOTEK' %}
				<th>Operasi</th>
				{% endif %}

		</thead>
		{% for row in data %}

		<tr>
            <td>{{ row.id_balai }}</td>
            <td>{{ row.alamat_balai }}</td>
            <td>{{ row.nama_balai }}</td>
            <td>{{ row.jenis_balai }}</td>
            <td>{{ row.telepon_balai }}</td>
            <td>{{ row.nama_apotek }}</td>
            {% if request.session.role == 'ADMIN_APOTEK' %}
            <td>
                <form action="{% url 'biru:update_balai_pengobatan' %}" method="get">
                    <input type="hidden" id="id_u_b" name="id_u_b" value="{{ row.id_balai }}">
                    <input type="submit" class="btn btn-success" value="Update">
                </form>

                <form action="{% url 'biru:delete_balai_pengobatan' %}" method="get">
                    <input type="hidden" id="id_d_b" name="id_d_b" value="{{ row.id_balai }}">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>			
</div>
{% endblock %}

biru/templates/CreateBalaiPengobatan.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create Balai Pengobatan - Farmakami{% endblock %}

{% block content %}

 <div class='jumbotron justify-content-center' align="center">
        <h1>Create Balai Pengobatan</h1>
        <hr>
        <h4>Farmakami</h4>
  </div>

  <div class="container d-flex justify-content-center" align="center">

        <form action="{% url 'biru:create_balai_pengobatan' %}" method="post">
          {% csrf_token %}
          {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
          {{ form.non_field_errors }}
          </div>
          {% endif %}

          <div class="form-group">

          <div>

          <h4>{{ form.alamat_balai.label }}</h4>
          <div class="input-group mb-3 ">   
            {{ form.alamat_balai }}
          </div>

          <h4>{{ form.nama_balai.label }}</h4>
          <div class="input-group mb-3">  
            {{ form.nama_balai }}
          </div>

          <h4>{{ form.jenis_balai.label }}</h4> 
          <div class="input-group mb-3"> 
            {{ form.jenis_balai }}
          </div>

          <h4>{{ form.telepon_balai.label }}</h4>
          <div class="input-group mb-3">  
            {{ form.telepon_balai }}
          </div>

          <h4>{{ form.id_apotek.label }}</h4>
          <div class="input-group mb-3">  
            {{ form.id_apotek }}
          </div>


      		</div>
          <input class="btn btn-outline-primary" type="submit" value="Create">

        </form>
   
  </div> 

{% endblock %}

biru/templates/CreateObat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create Obat - Farmakami{% endblock %}

{% block content %}

<div class='jumbotron justify-content-center' align="center">
		<h1>Create Obat</h1>
		<hr>
		<h4>Farmakami</h4>
</div>

<div class="container d-flex justify-content-center" align="center">
		<form action="{% url 'biru:create_obat' %}" method="POST">
			{% csrf_token %}
			{% if form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
			{{ form.non_field_errors }}
			</div>
			{% endif %}

			<div class="form-group">

				<h4>{{ form.id_merk_obat.label }}</h4> 
				<div class="input-group mb-3"> 
					{{ form.id_merk_obat }}
				</div>

				<h4>{{ form.netto.label }}</h4> 
				<div class="input-group mb-3"> 
					{{ form.netto }}
				</div>

				<h4>{{ form.dosis.label }}</h4> 
				<div class="input-group mb-3"> 
					{{ form.dosis }}
				</div>

				<h4>{{ form.aturan_pakai.label }}</h4> 
				<div class="input-group mb-3"> 
					{{ form.aturan_pakai }}
				</div>

				<h4>{{ form.kontraindikasi.label }}</h4> 
				<div class="input-group mb-3"> 
					{{ form.kontraindikasi }}
				</div>

				<h4>{{ form.bentuk_kesediaan.label }}</h4> 
				<div class="input-group mb-3"> 
					{{ form.bentuk_kesediaan }}
				</div>
		
			</div>

			<input class="btn btn-outline-primary" type="submit" value="Create">
		</form>
	 
</div> 
{% endblock %}

biru/templates/Obat.html
{% extends "base.html" %}
{% load static %}

{% block title %}Daftar Obat - Framakami{% endblock %}

   
   
{% block content %}

	<div class='jumbotron justify-content-center' align="center">
        <h1>Daftar Obat</h1>
        <hr>
        <h4>Farmakami</h4>
    </div>


	<div class="container d-flex justify-content-center" align="center">

	<table class="table table-hover" align="center">
		<thead class="thead-dark">
		
			<th>ID Obat</th>
			<th>ID Produk</th>
			<th>ID Merk Obat</th>
			<th>Netto</th>
			<th>Dosis</th>
			<th>Aturan Pakai</th>
			<th>Kontraindikasi</th>
			<th>Bentuk Ketersediaan</th>
			{% if request.session.role == 'ADMIN_APOTEK' or request.session.role == 'CS' %}
            <th>Operasi</th>
            {% endif %}

		</thead>
		{% for row in data %}

		<tr>
            <td>{{ row.id_obat }}</td>
            <td>{{ row.id_produk }}</td>
            <td>{{ row.id_merk_obat }}</td>
            <td>{{ row.netto }}</td>
            <td>{{ row.dosis }}</td>
            <td>{{ row.aturan_pakai }}</td>
            <td>{{ row.kontraindikasi }}</td>
            <td>{{ row.bentuk_kesediaan }}</td>
            {% if request.session.role == 'ADMIN_APOTEK' or request.session.role == 'CS' %}
            <td>
                <form action="{% url 'biru:update_obat' %}" method="get">
                    <input type="hidden" id="id_u_o" name="id_u_o" value="{{ row.id_obat }}">
                    <input type="submit" class="btn btn-success" value="Update">
                </form>

                <form action="{% url 'biru:delete_obat' %}" method="get">
                    <input type="hidden" id="id_d_o" name="id_d_o" value="{{ row.id_obat }}">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </td>
            {% endif %}
        </tr>
        {% endfor %}


	</table>
	
</div>
{% endblock %}

biru/templates/UpdateBalaiPengobatan.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Update Balai Pengobatan - Farmakami{% endblock %}

{% block content %}
<div class='jumbotron justify-content-center' align="center">
	<h1>Update Balai Pengobatan</h1>
	<hr>
	<h4>Farmakami</h4>
</div>

<div class="container d-flex justify-content-center" align="center">
	<form action="{% url 'biru:update_balai_pengobatan' %}" method="post">
		{% csrf_token %}
		{% if form.non_field_errors %}
		<div class="alert alert-danger" role="alert">
		{{ form.non_field_errors }}
		</div>
		{% endif %}

		<div>

			<h4>{{ form.id_balai.label }}</h4>	
			<div class="input-group mb-3"> 
				{{ form.id_balai }}
			</div>

			<h4>{{ form.alamat_balai.label }}</h4>
			<div class="input-group mb-3 "> 	
				{{ form.alamat_balai }}
			</div>

			<h4>{{ form.nama_balai.label }}</h4>
			<div class="input-group mb-3"> 	
				{{ form.nama_balai }}
			</div>

			<h4>{{ form.jenis_balai.label }}</h4>	
			<div class="input-group mb-3"> 
				{{ form.jenis_balai }}
			</div>

			<h4>{{ form.telepon_balai.label }}</h4>
			<div class="input-group mb-3"> 	
				{{ form.telepon_balai }}
			</div>

			<h4>{{ form.id_apotek.label }}</h4>
			<div class="input-group mb-3"> 	
				{{ form.id_apotek }}
			</div>

		</div>
		
		<input class="btn btn-outline-primary" type="submit" value="Update">
	</form>
</div>
{% endblock %}

biru/templates/UpdateObat.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Update Obat - Farmakami{% endblock %}

{% block content %}

<div class='jumbotron justify-content-center' align="center">
	<h1>Update Obat</h1>
	<hr>
	<h4>Farmakami</h4>
</div>

<div class="container d-flex justify-content-center" align="center">
	<form action="{% url 'biru:update_obat' %}" method="post">
		{% csrf_token %}
		{% if form.non_field_errors %}
		<div class="alert alert-danger" role="alert">
		{{ form.non_field_errors }}
		</div>
		{% endif %}

		<div class="form-group">

			<h4>{{ form.id_obat.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.id_obat }}
			</div>

			<h4>{{ form.id_produk.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.id_produk }}
			</div>

			<h4>{{ form.id_merk_obat.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.id_merk_obat }}
			</div>

			<h4>{{ form.netto.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.netto }}
			</div>

			<h4>{{ form.dosis.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.dosis }}
			</div>

			<h4>{{ form.aturan_pakai.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.aturan_pakai }}
			</div>

			<h4>{{ form.kontraindikasi.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.kontraindikasi }}
			</div>

			<h4>{{ form.bentuk_kesediaan.label }}</h4> 
			<div class="input-group mb-3"> 
				{{ form.bentuk_kesediaan }}
			</div>

		</div>
		<input class="btn btn-outline-primary" type="submit" value="Update">
	</form>
</div>
{% endblock %}