biru/urls.py
from django.urls import path, include
from .views import *
app_name = 'biru'
urlpatterns = [ 

	path('balai_pengobatan/', balai_pengobatan, name='balai_pengobatan'), 
	path('create_balai_pengobatan/', create_balai_pengobatan, name='create_balai_pengobatan'),
	path('update_balai_pengobatan/', update_balai_pengobatan, name='update_balai_pengobatan'),
	path('delete_balai_pengobatan/', delete_balai_pengobatan, name='delete_balai_pengobatan'),   
 
	path('obat/', obat, name='obat'), 
	path('create_obat/', create_obat, name='create_obat'),
	path('update_obat/', update_obat, name='update_obat'),
	path('delete_obat/', delete_obat, name='delete_obat'),

]

farmakami/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('biru/', include('biru.urls')),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('merah/', include('merah.urls')),
    path('ungu/', include('ungu.urls')),
    path('', include('fkauth.urls'))
]

hijau/urls.py
from django.urls import path, include
from .views import *

app_name = 'hijau'
urlpatterns = [
    path('createtp', CreateTP, name="createtp"),
    path('viewtp', ViewTP, name="viewtp"),
    path('updatetp/<id>/', UpdateTP, name="updatetp"),
    path('deletetp/<id>/', DeleteTP, name="deletetp")

]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    </head>
    <body>
        <div class="d-flex flex-column justify-content-center align-items-center" id="spinner" style="display:inline; height:100vh">
            <div class="d-flex justify-content-center align-items-center mb-4" style="width:100%">
                <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
            <div class="justify-content-center" align="middle">
                <h3>Farmakami</h3>
                <hr>
                <p>"We should be concerned not only about the health of individual patients, but also the health of our entire society."</p>
                <em>—Ben Carson</em>
            </div>
        </div>
        <div id="core" style="display:none">
            {% include 'navbar.html' %}
            {% block content %}

            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="  crossorigin="anonymous"></script>
        <script src="{% static 'js/logic.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid d-flex mr-auto">
        <a class="navbar-brand" href="{% url 'home' %}">
            <i class="d-inline-block align-center fa fa-medkit"></i>
            FarmaKami
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav justify-content-start">
        {% if request.session.email %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        BP/Apotek
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_APOTEK' %}
        <a class="dropdown-item" href="{% url 'biru:create_balai_pengobatan' %}">Buat Balai Pengobatan</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'biru:balai_pengobatan' %}">Daftar Balai Pengobatan</a>
        {% if request.session.role == 'ADMIN_APOTEK' %}
        <a class="dropdown-item" href="{% url 'create_apotek' %}">Buat Apotek</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'apotek' %}">Daftar Apotek</a>
        </div>
        </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Transaksi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_APOTEK' %}
        <a class="dropdown-item" href="{% url 'hijau:createtp' %}">Buat Transaksi Pembelian</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'hijau:viewtp' %}">Daftar Transaksi Pembelian</a>
        {% if request.session.role == 'ADMIN_APOTEK' or request.session.role == 'CS' %}
        <a class="dropdown-item" href="{% url 'create-transaksiresep' %}">Buat Transaksi Resep</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'transaksiresep' %}">Daftar Transaksi Resep</a>
        </div>
        </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Produk Apotek
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_APOTEK' %}
        <a class="dropdown-item" href="{% url 'create_produk_apotek' %}">Buat Produk Apotek</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'produk_apotek' %}">Daftar Produk Apotek</a>
        </div>
        </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Produk Dibeli
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_APOTEK' %}
        <a class="dropdown-item" href="{% url 'create-listprodukdibeli' %}">Buat List Produk Dibeli</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'listprodukdibeli' %}">Daftar Produk Dibeli</a>
        </div>
        </li>

        {% if request.session.role == 'ADMIN_APOTEK' or request.session.role == 'KURIR' %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Pengantaran
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_APOTEK' %}
        <a class="dropdown-item" href="{% url 'create-pengantaranfarmasi' %}">Buat Pengantaran Farmasi</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'pengantaranfarmasi' %}">Daftar Pengantaran</a>
        </div>
        </li>
        {% endif %}


        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Produk
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_APOTEK' or request.session.role == 'CS' %}
        <a class="dropdown-item" href="{% url 'biru:create_obat' %}">Buat Obat</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'biru:obat' %}">Daftar Obat</a>
        {% if request.session.role == 'ADMIN_APOTEK' or request.session.role == 'CS' %}
        <a class="dropdown-item" href="{% url 'create-alatmedis' %}">Buat Alat Medis</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'alatmedis' %}">Daftar Alat Medis</a>
        </div>
        </li>
        </ul>
        {% endif %}
        <ul class="d-flex align-items-center nav navbar-nav ml-auto justify-content-end">
        {% if request.session.email %}
        <li class="navbar-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" align="right" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span>
        <strong>{{ request.session.nama }}</strong> <i class="fa fa-user"></i>
        </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
        </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
        </ul>
        </div>
    </div>
</nav>