biru/urls.py
from django.urls import path, include
from .views import *
app_name = 'biru'
urlpatterns = [ 

	path('balai_pengobatan/', balai_pengobatan, name='balai_pengobatan'), 
	path('create_balai_pengobatan/', create_balai_pengobatan, name='create_balai_pengobatan'),
	path('update_balai_pengobatan/', update_balai_pengobatan, name='update_balai_pengobatan'),
	path('delete_balai_pengobatan/', delete_balai_pengobatan, name='delete_balai_pengobatan'),   
 
	path('obat/', obat, name='obat'), 
	path('create_obat/', create_obat, name='create_obat'),
	path('update_obat/', update_obat, name='update_obat'),
	path('delete_obat/', delete_obat, name='delete_obat'),

]

farmakami/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('biru/', include('biru.urls')),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('merah/', include('merah.urls')),
    path('ungu/', include('ungu.urls')),
    path('', include('fkauth.urls'))
]

hijau/urls.py
from django.urls import path, include
from .views import *

app_name = 'hijau'
urlpatterns = [
    path('createtp', CreateTP, name="createtp"),
    path('viewtp', ViewTP, name="viewtp"),
    path('updatetp/<id>/', UpdateTP, name="updatetp"),
    path('deletetp/<id>/', DeleteTP, name="deletetp")

]

hijau/models.py
from django.db import models

# Create your models here.

hijau/forms.py
from django import forms
from django.db import connection

class TPForms(forms.Form):
    id_transaksi_pembelian = forms.CharField(label = 'ID Transaksi Pembelian', 
        max_length = 10, widget=forms.TextInput(attrs={'class' : 'form-idtp'}))

    waktu_pembelian = forms.DateTimeField(label = 'Waktu Pembelian', 
        required = True, widget = forms.DateTimeInput(attrs = {"class": "form-tanggal", "type":"date"}))
        
    total_pembayaran = forms.IntegerField(label = 'Total Pembayaran', 
        widget=forms.NumberInput(attrs={'class' : 'form-tp'}))

    id_konsumen = forms.CharField(label = 'ID Konsumen', 
        max_length = 10, widget=forms.TextInput(attrs={'class' : 'form-idk'}))
        
class CreateForms(forms.Form):
    ID_KONSUMEN_CHOICES = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT id_konsumen, id_konsumen FROM KONSUMEN")
            self.fields['id_konsumen'].choices = cursor.fetchall()
    
    id_konsumen= forms.ChoiceField(choices=ID_KONSUMEN_CHOICES, label='ID Konsumen', widget=forms.Select(attrs= {"class":"form-control"}))

hijau/views.py
from django.shortcuts import render, redirect
from .forms import TPForms, CreateForms
from merah.views import user_login_required

from django.db import connection
from django.db import IntegrityError
from collections import namedtuple
import datetime
import os
# Create your views here.

#From Django Docs
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

# @user_login_required
def ViewTP(request):
    role = request.session['role']
    dataset = ''
    with connection.cursor() as cursor:
        if role =='KONSUMEN':
            cursor.execute("SELECT * FROM KONSUMEN WHERE email=%s", [request.session.get("email")])
            dataset = namedtuplefetchall(cursor)
            cursor.execute("SELECT * FROM TRANSAKSI_PEMBELIAN WHERE id_konsumen='" + dataset[0].id_konsumen + "'")
            dataset = namedtuplefetchall(cursor)
            context = {'table': dataset}
        else:
            cursor.execute("SELECT * FROM TRANSAKSI_PEMBELIAN")
            dataset = namedtuplefetchall(cursor)
            context = {'table': dataset}
        return render(request,"viewTP.html", context)

@user_login_required
def UpdateTP(request, id):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            form = CreateForms(request.POST)
            if form.is_valid():
                id_konsumen = form.cleaned_data['id_konsumen']
                waktu_pembelian = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                id_transaksi_pembelian = request.POST.get("id_transaksi_pembelian")
                if id_konsumen != id:
                    cursor.execute("UPDATE TRANSAKSI_PEMBELIAN SET id_konsumen =%s where id_transaksi_pembelian =%s", [id_konsumen, id])
                    cursor.execute("UPDATE TRANSAKSI_PEMBELIAN SET waktu_pembelian=%s where id_transaksi_pembelian=%s", [waktu_pembelian, id])
                return redirect('/hijau/viewtp')
        cursor.execute("SELECT waktu_pembelian FROM TRANSAKSI_PEMBELIAN where id_transaksi_pembelian=%s", [id])
        waktu_pembelian = cursor.fetchone()[0]

        cursor.execute("SELECT total_pembayaran FROM TRANSAKSI_PEMBELIAN where id_transaksi_pembelian=%s", [id])
        total_pembayaran = cursor.fetchone()[0]

        form = CreateForms()
        context = {'form': form, 'id':id, 'waktu_pembelian':waktu_pembelian, 'total_pembayaran':total_pembayaran}
        return render(request, "updateTP.html", context)

@user_login_required
def DeleteTP(request, id):
    with connection.cursor() as cursor:
        try:
            cursor.execute("DELETE FROM TRANSAKSI_PEMBELIAN WHERE id_transaksi_pembelian=%s",[id])
        except IntegrityError:
            pass
        return redirect('/hijau/viewtp')

@user_login_required
def CreateTP(request):
    with connection.cursor() as cursor:
        if request.method =='POST':
            form = CreateForms(request.POST)
            if form.is_valid():
                id_konsumen = form.cleaned_data['id_konsumen']
                waktu_pembelian = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                cursor.execute("SELECT COUNT(*) FROM TRANSAKSI_PEMBELIAN")
                jumlahid = cursor.fetchone()[0]
                id_transaksi_baru = jumlahid+1
                cursor.execute("INSERT INTO TRANSAKSI_PEMBELIAN VALUES (%s, %s, %s, %s)", 
                                [id_transaksi_baru, waktu_pembelian, 0, id_konsumen])
        form = CreateForms()
        context = {'form':form}
        return render(request, 'createTP.html', context)

hijau/templates/createTP.html
{% extends "base.html" %}

{% block title %}
Farmakami - Create TP
{% endblock %}

{% block content %}
<style>
label{
    width: 500px;
    display: inline-block;
}

input{
    width: 465px;
}
</style>
<div class="jumbotron">
    {% if request.session.role == "ADMIN_APOTEK" %}      
    <h1 class="display-4">Create Transaksi Pembelian - Admin</h1>
    {% else %}
    <h1 class="display-4">Create Transaksi Pembelian</h1>
    {% endif %}
    <p class="lead font-italic">FarmaKami Indonesia</p>
    <hr class="my-4">
</div>

<div class="container jumbotron">  
    {% if request.session.role == "ADMIN_APOTEK" %}       
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary" type="submit">Submit</button>
    </form>
    {% else %}
    <p class="lead font-italic">Maaf, anda tidak memiliki akses ke laman ini.</p>
    {% endif %}
</div>
{% endblock content %}

hijau/templates/updateTP.html
{% extends "base.html" %}

{% block title %}
Farmakami - Update TP
{% endblock %}

{% block content %}
<style>
    .backbutton{
        width: 5em;
        margin-top: -2em;
    }
</style>

<div class="jumbotron">
    <h1 class="display-4">Update Transaksi Pembelian</h1>
    <p class="lead font-italic">FarmaKami Indonesia</p>
    <hr class="my-4">
</div>
<a href="{% url 'hijau:viewtp' %}">
        <img class="backbutton" src="https://pngimage.net/wp-content/uploads/2018/05/back-logo-png-6.png">
</a>
<div class="container jumbotron">
    <form method="POST">
        <div class="form-group">
            <label for="exampleFormControlSelect1">ID Transaksi Pembelian</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option value="{{ id }}"> {{ id }}</option>
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Waktu Pembelian</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option value="{{ waktu_pembelian }}"> {{ waktu_pembelian }}</option>
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Total Pembayaran</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option value="{{ total_pembayaran }}"> {{ total_pembayaran }}</option>
            </select>
        </div>
        <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <button class="btn btn-outline-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

hijau/templates/viewTP.html
{% extends "base.html" %}

{% block title %}
List TP - Farmakami
{% endblock %}

{% block content %}
<div class="jumbotron">
  {% if request.session.role == 'ADMIN_APOTEK' %}
  <h1 class="display-4">List Transaksi Pembelian - Admin</h1>
  {% else %}
  <h1 class="display-4">List Transaksi Pembelian</h1>
  {% endif %}
  <p class="lead font-italic">FarmaKami Indonesia</p>
  <hr class="my-4">
</div>
{% if request.session.role == 'ADMIN_APOTEK' %}
<div class="container">
    <table class="table table-striped table table-hover">
        <thead>
          <tr>
            <th scope="col">ID Transaksi Pembelian</th>
            <th scope="col">Waktu Pembelian</th>
            <th scope="col">Total Pembayaran</th>
            <th scope="col">ID Konsumen</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
        {% for item in table %}
          <tr>
            <td>{{ item.id_transaksi_pembelian }}</td>
            <td>{{ item.waktu_pembelian }}</td>
            <td>{{ item.total_pembayaran }}</td>
            <td>{{ item.id_konsumen }}</td>
            <td>
                <a href="{% url 'hijau:updatetp' item.id_transaksi_pembelian %}" class="btn btn-outline-primary" role="button">Update</a>
                <a href="{% url 'hijau:deletetp' item.id_transaksi_pembelian %}" class="btn btn-outline-primary" role="delete">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="container">
    <table class="table table-striped table table-hover">
        <thead>
          <tr>
            <th scope="col">ID Transaksi Pembelian</th>
            <th scope="col">Waktu Pembelian</th>
            <th scope="col">Total Pembayaran</th>
            <th scope="col">ID Konsumen</th>
          </tr>
        </thead>
        <tbody>
        {% for item in table %}
          <tr>
            <td>{{ item.id_transaksi_pembelian }}</td>
            <td>{{ item.waktu_pembelian }}</td>
            <td>{{ item.total_pembayaran }}</td>
            <td>{{ item.id_konsumen }}</td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}


{% endblock content %}